/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Evaluation, Criterion, Employee } from '../types';

export interface ProductionInputParams {
  empCode: string;
  empName?: string;
  period: string;
  producedUnits: number;
  targetUnits: number;
  actualCycleTimeSec: number;
  standardCycleTimeSec: number;
  scrapUnits: number;
  workingHours: number;
  downtimeHours: number;
  notes?: string;
}

export interface ProductionCalculationResult {
  efficiencyRate: number;
  productionScore: number;
  cycleTimeVarianceSec: number;
  cycleTimeImprovementRate: number;
  cycleTimeScore: number;
  scrapRate: number;
  ppm: number;
  scrapScore: number;
  qualityRate: number;
  availabilityRate: number;
  performanceRate: number;
  oeeRate: number;
  oeeScore: number;
  overallKpiScore: number;
  autoGeneratedSummary: string;
  badgeLevel: 'استثنایی (A+)' | 'فراتر از انتظار (A)' | 'در حد انتظار (B)' | 'نیازمند بهبود (C)' | 'بحرانی (D)';
}

export function calculateProductionMetrics(params: ProductionInputParams): ProductionCalculationResult {
  const {
    producedUnits = 0,
    targetUnits = 0,
    actualCycleTimeSec = 0,
    standardCycleTimeSec = 0,
    scrapUnits = 0,
    workingHours = 0,
    downtimeHours = 0
  } = params;

  const safeTarget = targetUnits > 0 ? targetUnits : 1;
  const efficiencyRate = Number(((producedUnits / safeTarget) * 100).toFixed(2));
  let productionScore = 3;
  if (efficiencyRate >= 105) productionScore = 5;
  else if (efficiencyRate >= 100) productionScore = 4;
  else if (efficiencyRate >= 92) productionScore = 3;
  else if (efficiencyRate >= 80) productionScore = 2;
  else productionScore = 1;

  const cycleTimeVarianceSec = standardCycleTimeSec > 0 && actualCycleTimeSec > 0
    ? Number((standardCycleTimeSec - actualCycleTimeSec).toFixed(2))
    : 0;

  const cycleTimeImprovementRate = standardCycleTimeSec > 0 && actualCycleTimeSec > 0
    ? Number((((standardCycleTimeSec - actualCycleTimeSec) / standardCycleTimeSec) * 100).toFixed(2))
    : 0;

  let cycleTimeScore = 3;
  if (cycleTimeImprovementRate >= 5) cycleTimeScore = 5;
  else if (cycleTimeImprovementRate >= 0) cycleTimeScore = 4;
  else if (cycleTimeImprovementRate >= -7) cycleTimeScore = 3;
  else if (cycleTimeImprovementRate >= -15) cycleTimeScore = 2;
  else cycleTimeScore = 1;

  const safeProduced = producedUnits > 0 ? producedUnits : 1;
  const safeScrap = Math.max(0, scrapUnits);
  const scrapRate = Number(((safeScrap / safeProduced) * 100).toFixed(2));
  const ppm = Math.round(scrapRate * 10000);
  const qualityRate = Number(Math.max(0, 100 - scrapRate).toFixed(2));

  let scrapScore = 3;
  if (scrapRate <= 0.8) scrapScore = 5;
  else if (scrapRate <= 1.5) scrapScore = 4;
  else if (scrapRate <= 2.5) scrapScore = 3;
  else if (scrapRate <= 4.0) scrapScore = 2;
  else scrapScore = 1;

  const safeWorkingHours = workingHours > 0 ? workingHours : 160;
  const safeDowntime = Math.min(safeWorkingHours, Math.max(0, downtimeHours));
  const availabilityRate = Number((((safeWorkingHours - safeDowntime) / safeWorkingHours) * 100).toFixed(2));

  let performanceRate = 100;
  if (standardCycleTimeSec > 0 && actualCycleTimeSec > 0) {
    performanceRate = Number(Math.min(115, (standardCycleTimeSec / actualCycleTimeSec) * 100).toFixed(2));
  } else if (efficiencyRate > 0) {
    performanceRate = Number(Math.min(115, efficiencyRate).toFixed(2));
  }

  const oeeRate = Number(((availabilityRate * performanceRate * qualityRate) / 10000).toFixed(2));
  let oeeScore = 3;
  if (oeeRate >= 85) oeeScore = 5;
  else if (oeeRate >= 75) oeeScore = 4;
  else if (oeeRate >= 65) oeeScore = 3;
  else if (oeeRate >= 50) oeeScore = 2;
  else oeeScore = 1;

  const overallKpiScore = Number(
    ((productionScore * 0.35) + (cycleTimeScore * 0.25) + (scrapScore * 0.25) + (oeeScore * 0.15)).toFixed(2)
  );

  let badgeLevel: ProductionCalculationResult['badgeLevel'] = 'در حد انتظار (B)';
  if (overallKpiScore >= 4.5) badgeLevel = 'استثنایی (A+)';
  else if (overallKpiScore >= 3.8) badgeLevel = 'فراتر از انتظار (A)';
  else if (overallKpiScore >= 2.8) badgeLevel = 'در حد انتظار (B)';
  else if (overallKpiScore >= 2.0) badgeLevel = 'نیازمند بهبود (C)';
  else badgeLevel = 'بحرانی (D)';

  const cycleDiffText = cycleTimeVarianceSec >= 0 
    ? `${Math.abs(cycleTimeVarianceSec)} ثانیه سریع‌تر (+${cycleTimeImprovementRate}٪)`
    : `${Math.abs(cycleTimeVarianceSec)} ثانیه کندتر (${cycleTimeImprovementRate}٪)`;

  const autoGeneratedSummary = `تولید ${producedUnits.toLocaleString('fa-IR')} عدد با راندمان ${efficiencyRate}٪ | زمان چرخه ${actualCycleTimeSec}s در برابر استاندارد ${standardCycleTimeSec}s (${cycleDiffText}) | ضایعات ${scrapRate}٪ (${ppm.toLocaleString('fa-IR')} PPM) | توقف خط ${safeDowntime} ساعت | شاخص OEE: ${oeeRate}٪ | نمره کل شاخص‌ها: ${overallKpiScore} از ۵`;

  return {
    efficiencyRate,
    productionScore,
    cycleTimeVarianceSec,
    cycleTimeImprovementRate,
    cycleTimeScore,
    scrapRate,
    ppm,
    scrapScore,
    qualityRate,
    availabilityRate,
    performanceRate,
    oeeRate,
    oeeScore,
    overallKpiScore,
    autoGeneratedSummary,
    badgeLevel
  };
}

export function applyProductionMetricsToEvaluation(
  evaluation: Evaluation,
  criteria: Criterion[],
  calculation: ProductionCalculationResult,
  params: ProductionInputParams
): Evaluation {
  const updatedScores = evaluation.scores.map(scoreItem => {
    const crit = criteria.find(c => c.id === scoreItem.cid);
    if (!crit) return scoreItem;
    const critName = (crit.name || '').toLowerCase();
    const critCode = (crit.code || '').toUpperCase();

    if (critCode === 'K-01' || critName.includes('برنامه') || critName.includes('راندمان')) {
      return {
        ...scoreItem,
        value: calculation.productionScore,
        doc: `تولید واقعی: ${params.producedUnits.toLocaleString('fa-IR')} در برابر برنامه ${params.targetUnits.toLocaleString('fa-IR')} (راندمان: ${calculation.efficiencyRate}٪)`
      };
    }

    if (critCode === 'K-11' || critName.includes('ستاپ') || critName.includes('قالب') || critName.includes('چرخه')) {
      return {
        ...scoreItem,
        value: calculation.cycleTimeScore,
        doc: `زمان واقعی چرخه: ${params.actualCycleTimeSec} ثانیه (استاندارد: ${params.standardCycleTimeSec}s | بهبود: ${calculation.cycleTimeImprovementRate}٪)`
      };
    }

    if (critCode === 'K-04' || critCode === 'Q-01' || critName.includes('ضایعات') || critName.includes('افت')) {
      return {
        ...scoreItem,
        value: calculation.scrapScore,
        doc: `نرخ ضایعات قطعه: ${calculation.scrapRate}٪ (${params.scrapUnits.toLocaleString('fa-IR')} عدد نامنطبق | ${calculation.ppm.toLocaleString('fa-IR')} PPM)`
      };
    }

    if (critCode === 'K-06' || critName.includes('oee') || critName.includes('اثربخشی کلی')) {
      return {
        ...scoreItem,
        value: calculation.oeeScore,
        doc: `شاخص اثربخشی کلی تجهیزات: ${calculation.oeeRate}٪ (دسترس‌پذیری: ${calculation.availabilityRate}٪ | عملکرد: ${calculation.performanceRate}٪ | کیفیت: ${calculation.qualityRate}٪)`
      };
    }

    if (critCode === 'K-07' || critName.includes('توقف')) {
      const downtimeScore = params.downtimeHours <= 2 ? 5 : params.downtimeHours <= 5 ? 4 : params.downtimeHours <= 10 ? 3 : params.downtimeHours <= 18 ? 2 : 1;
      return {
        ...scoreItem,
        value: downtimeScore,
        doc: `توقفات ثبت شده: ${params.downtimeHours} ساعت از مجموع ${params.workingHours} ساعت شیفت کاری`
      };
    }

    return scoreItem;
  });

  return {
    ...evaluation,
    scores: updatedScores,
    note: evaluation.note 
      ? `${evaluation.note}\n\n[ثبت خودکار داده‌های خط]: ${calculation.autoGeneratedSummary}`
      : `[ثبت خودکار داده‌های خط]: ${calculation.autoGeneratedSummary}`
  };
}
